/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
        
import Config.koneksi;
import View.Menu;
import Model.Session;
import View.ratingUlasan;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author yehezkiel
 */
public class login extends javax.swing.JFrame {
    
    private Connection conn;


    public login() {
        conn = koneksi.getConnection();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_login = new javax.swing.JLabel();
        p_pesan = new javax.swing.JPanel();
        lbl_welcome = new javax.swing.JLabel();
        lbl_welcome2 = new javax.swing.JLabel();
        lbl_welcome3 = new javax.swing.JLabel();
        btn_register = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        t_username = new javax.swing.JTextField();
        t_password = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIPIT - LOGIN");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/logo-sipit4.png")).getImage());
        setLocation(new java.awt.Point(0, 0));
        setName("SIPIT"); // NOI18N
        setSize(new java.awt.Dimension(854, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(854, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_login.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lbl_login.setText("Login");
        jPanel1.add(lbl_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, -1));

        p_pesan.setBackground(new java.awt.Color(0, 51, 255));

        lbl_welcome.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        lbl_welcome.setForeground(new java.awt.Color(255, 255, 255));
        lbl_welcome.setText("Hello,");

        lbl_welcome2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        lbl_welcome2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_welcome2.setText("Welcome to SIPIT");

        lbl_welcome3.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lbl_welcome3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_welcome3.setText("Aplikasi E-book Terbaik untuk Anda");

        javax.swing.GroupLayout p_pesanLayout = new javax.swing.GroupLayout(p_pesan);
        p_pesan.setLayout(p_pesanLayout);
        p_pesanLayout.setHorizontalGroup(
            p_pesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_pesanLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(p_pesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_welcome2)
                    .addComponent(lbl_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_welcome3))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        p_pesanLayout.setVerticalGroup(
            p_pesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_pesanLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(lbl_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_welcome2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_welcome3)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        jPanel1.add(p_pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 480));

        btn_register.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        jPanel1.add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        btn_login.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        btn_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_loginKeyPressed(evt);
            }
        });
        jPanel1.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 260, 80, -1));

        t_username.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        t_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_username.setText("username");
        t_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_usernameFocusLost(evt);
            }
        });
        t_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(t_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 220, 40));

        t_password.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        t_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_password.setText("password");
        t_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_passwordFocusLost(evt);
            }
        });
        t_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(t_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 220, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 740, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        register reg = new register();
        reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_registerActionPerformed

    
    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String username = t_username.getText();
        String password = t_password.getText();
        
        if(username.isEmpty() || password.isEmpty() || username.equals("username") || password.equals("password")) {
            JOptionPane.showMessageDialog(this, "Username atau Password tidak boleh kosong!", "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (authenticate(username, password)) {
//            JOptionPane.showMessageDialog(this, "Login berhasil!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            Session.username = username;
            Menu menu = new Menu(); // Mengarahkan ke frame Menu
            menu.setVisible(true);
            this.dispose(); // Menutup frame login
        } else {
            JOptionPane.showMessageDialog(this, "Username atau password salah.", "Login Gagal", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_btn_loginActionPerformed

        private boolean authenticate(String username, String password) {

        try{
            String query = "SELECT * FROM pengguna WHERE username = ? AND password = ?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, username);
            stmt.setString(2, password);
            ResultSet rs = stmt.executeQuery();
            
            return rs.next();
        } catch (Exception e) {
            Logger.getLogger(ratingUlasan.class.getName()).log(Level.SEVERE,null,e);
            return false;
        }
      }
    
    private void t_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_passwordActionPerformed

    }//GEN-LAST:event_t_passwordActionPerformed

    private void t_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusGained
       String pass=t_username.getText();
       if(pass.equals("username")) {
           t_username.setText("");
       }
    }//GEN-LAST:event_t_usernameFocusGained

    private void t_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusLost
       String pass=t_username.getText();
       if(pass.equals("") || pass.equals("username")) {
           t_username.setText("username");
       }
    }//GEN-LAST:event_t_usernameFocusLost

    private void t_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passwordFocusLost
       String pass=t_password.getText();
       if(pass.equals("") || pass.equals("password")) {
           t_password.setText("password");
       }
    }//GEN-LAST:event_t_passwordFocusLost

    private void t_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passwordFocusGained
       String pass=t_password.getText();
       if(pass.equals("password")) {
           t_password.setText("");
       }
    }//GEN-LAST:event_t_passwordFocusGained

    private void t_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_usernameActionPerformed

    private void btn_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_loginKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_loginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_register;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JLabel lbl_welcome2;
    private javax.swing.JLabel lbl_welcome3;
    private javax.swing.JPanel p_pesan;
    private javax.swing.JTextField t_password;
    private javax.swing.JTextField t_username;
    // End of variables declaration//GEN-END:variables
}
