/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Session;

/**
 *
 * @author aidil
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Menu() {
        initComponents();
        lbl_user.setText("Hello!! " + Session.username);
    }

//    public Menu() {
//        initComponents();
//        lbl_user.setText("Hello "+ username +"!!");
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        nav = new javax.swing.JPanel();
        nav_ratingulasan = new javax.swing.JLabel();
        nav_home = new javax.swing.JLabel();
        nav_bookmark = new javax.swing.JLabel();
        nav_logout = new javax.swing.JLabel();
        Dashboard = new javax.swing.JPanel();
        lbl_welcome2 = new javax.swing.JLabel();
        lbl_welcome = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        contain = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIPIT - MENU");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/logo-sipit4.png")).getImage());
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(854, 529));
        setName("SIPIT"); // NOI18N
        setSize(new java.awt.Dimension(854, 529));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setMinimumSize(new java.awt.Dimension(854, 529));
        panel.setPreferredSize(new java.awt.Dimension(854, 529));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nav.setBackground(new java.awt.Color(0, 0, 255));

        nav_ratingulasan.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        nav_ratingulasan.setForeground(new java.awt.Color(255, 255, 255));
        nav_ratingulasan.setText("Rating Ulasan");
        nav_ratingulasan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_ratingulasanMouseClicked(evt);
            }
        });

        nav_home.setFont(new java.awt.Font("Poppins", 1, 15)); // NOI18N
        nav_home.setForeground(new java.awt.Color(255, 255, 255));
        nav_home.setText("Home");

        nav_bookmark.setFont(new java.awt.Font("Poppins", 0, 15)); // NOI18N
        nav_bookmark.setForeground(new java.awt.Color(255, 255, 255));
        nav_bookmark.setText("Bookmark");
        nav_bookmark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_bookmarkMouseClicked(evt);
            }
        });

        nav_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        nav_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout navLayout = new javax.swing.GroupLayout(nav);
        nav.setLayout(navLayout);
        navLayout.setHorizontalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(nav_home)
                .addGap(18, 18, 18)
                .addComponent(nav_bookmark)
                .addGap(18, 18, 18)
                .addComponent(nav_ratingulasan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 518, Short.MAX_VALUE)
                .addComponent(nav_logout)
                .addGap(48, 48, 48))
        );
        navLayout.setVerticalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nav_logout)
                    .addGroup(navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nav_ratingulasan)
                        .addComponent(nav_home)
                        .addComponent(nav_bookmark)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panel.add(nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 60));

        Dashboard.setBackground(new java.awt.Color(204, 204, 204));

        lbl_welcome2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lbl_welcome2.setText("mulai membaca sekarang!");

        lbl_welcome.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lbl_welcome.setText("Temukan E-book favorit Anda,");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/book.png"))); // NOI18N

        lbl_user.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        lbl_user.setText("Hello");

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardLayout.createSequentialGroup()
                .addContainerGap(741, Short.MAX_VALUE)
                .addComponent(logo)
                .addGap(55, 55, 55))
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_welcome2)
                    .addComponent(lbl_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(logo)
                .addGap(18, 18, 18)
                .addComponent(lbl_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_welcome2)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        panel.add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 860, 320));

        contain.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setText("REKOMENDASI");

        javax.swing.GroupLayout containLayout = new javax.swing.GroupLayout(contain);
        contain.setLayout(containLayout);
        containLayout.setHorizontalGroup(
            containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containLayout.createSequentialGroup()
                .addContainerGap(376, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(380, 380, 380))
        );
        containLayout.setVerticalGroup(
            containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        panel.add(contain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 850, 150));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nav_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_logoutMouseClicked
        login login = new login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nav_logoutMouseClicked

    private void nav_bookmarkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_bookmarkMouseClicked
        bookmark  bookmark = new bookmark();
        bookmark.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nav_bookmarkMouseClicked

    private void nav_ratingulasanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_ratingulasanMouseClicked
        ratingUlasan  ratingUlasan = new ratingUlasan();
        ratingUlasan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nav_ratingulasanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel contain;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JLabel lbl_welcome2;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel nav;
    private javax.swing.JLabel nav_bookmark;
    private javax.swing.JLabel nav_home;
    private javax.swing.JLabel nav_logout;
    private javax.swing.JLabel nav_ratingulasan;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
